# Generated by Django 4.1.3 on 2022-12-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('-created',)},
        ),
    ]
