# Generated by Django 4.1 on 2022-10-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'تنظیمات', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
    ]
