# Generated by Django 4.1 on 2022-10-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sitesetting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'شماره تماس', 'verbose_name_plural': 'شماره تماس ها'},
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='Phone',
            new_name='phone',
        ),
    ]
