# Generated by Django 4.1 on 2022-10-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sitesetting_additional_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
