# Generated by Django 4.1 on 2022-10-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sitesetting_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
