# Generated by Django 4.1.3 on 2022-11-08 10:09

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sitesetting_about_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('banner', models.ImageField(upload_to=main.models.slider_name_generator, verbose_name='بنر')),
                ('text', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر های سایت',
            },
        ),
    ]
