# Generated by Django 4.1.3 on 2022-11-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url',
            field=models.URLField(default='', verbose_name='لینک'),
            preserve_default=False,
        ),
    ]
