# Generated by Django 4.1.3 on 2022-12-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartproducts_product_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_series',
            field=models.UUIDField(default=0, verbose_name='کد رهگیری'),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pay_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
