# Generated by Django 4.1.3 on 2022-12-17 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_cart_series_cart_is_paid_cart_pay_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_series',
        ),
    ]
