# Generated by Django 4.1.3 on 2022-12-17 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productview_ip'),
        ('cart', '0006_remove_cart_cart_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', unique=True, verbose_name='محصول'),
        ),
    ]
