# Generated by Django 4.1.3 on 2022-12-17 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cartproducts_count_alter_cartproducts_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproducts',
            name='product_price',
        ),
    ]
