# Generated by Django 4.1.3 on 2022-12-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_cartproducts_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='قیمت نهایی'),
        ),
    ]
