# Generated by Django 4.1.3 on 2022-12-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_rename_final_price_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, verbose_name='وضعیت پرداخت'),
        ),
    ]
