# Generated by Django 4.1.3 on 2022-12-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productview_ip'),
        ('cart', '0012_alter_cart_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproducts',
            options={'ordering': ('id',), 'verbose_name': 'محصول سبد خرید', 'verbose_name_plural': 'محصولات سبد خرید'},
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول'),
        ),
    ]
