# Generated by Django 4.1 on 2022-08-24 13:34

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='')),
                ('english_title', models.CharField(max_length=64, verbose_name='')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='')),
                ('english_title', models.CharField(max_length=64, verbose_name='')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='')),
                ('english_title', models.CharField(max_length=150, verbose_name='')),
                ('slug', models.SlugField(max_length=150, verbose_name='')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('modified', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(max_length=5, verbose_name='')),
                ('about', models.TextField(blank=True, null=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='')),
                ('category', models.ManyToManyField(to='products.category', verbose_name='')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=products.models.product_name_generator)),
                ('is_default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
