# Generated by Django 4.1 on 2022-08-24 13:49

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test',
            field=django_jalali.db.models.jDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='english_title',
            field=models.CharField(max_length=64, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=64, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='category',
            name='english_title',
            field=models.CharField(max_length=64, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=64, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='درباره محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='products.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(max_length=5, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='english_title',
            field=models.CharField(max_length=150, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان'),
        ),
    ]
