# Generated by Django 4.1 on 2022-08-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_test_alter_brand_english_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test',
        ),
    ]
