# Generated by Django 4.1 on 2022-08-30 18:09

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_count_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
