# Generated by Django 4.1 on 2022-08-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_created_alter_product_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpicture',
            options={'ordering': ('is_default',), 'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصولات'},
        ),
    ]
