# Generated by Django 4.1 on 2022-08-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productpicture_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpicture',
            options={'ordering': ('-is_default',), 'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصولات'},
        ),
    ]
