# Generated by Django 4.1.3 on 2022-11-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='modified',
        ),
    ]
