# Generated by Django 4.1.3 on 2022-12-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productcomment_product_alter_productcomment_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ('-created',)},
        ),
    ]
